<?php

return [
    'rdc' => 'manoir/rdc',
    'salon' => 'manoir/salon',
    'aile' => 'manoir/aile',
    'etage' => 'manoir/etage',
    'chambre' => 'manoir/chambre',
    'coffret' => 'manoir/coffret',
    'papier' => 'manoir/papier',
    'bureau' => 'manoir/bureau',
    'bureauprive' => 'manoir/bureauprive',
    'bureauprive2' => 'manoir/bureauprive2',
    'courtcircuit' => 'manoir/courtcircuit',
    'cuves' => 'manoir/cuves',
    'cavesecrete' => 'manoir/cavesecrete',
    'pensees' => 'manoir/pensees',
    'shoggoth' => 'manoir/shoggoth',
    'fin' => 'fin',
    'bibliotheque' => 'manoir/bibliotheque',
    'chambres' => 'manoir/chambres',
    'grenier' => 'manoir/grenier',
    'cave' => 'manoir/cave',
    'tableaubrule' => 'manoir/tableaubrule',
    'jardin' => 'manoir/jardin',
    'maisongaspard' => 'manoir/maisongaspard',
    'chenil' => 'manoir/chenil',
    'serre' => 'manoir/serre',
    'jour2' => 'manoir/jour2',
    'intrusion' => 'manoir/intrusion',
    'nuit' => 'manoir/nuit',
    'matin' => 'manoir/matin',
    'manoir107parkavenue' => 'manoir/107parkavenue',
    'pellingtonrdc' => '107parkavenue/rdc',
    'pellingtonvestibule' => '107parkavenue/vestibule',
    'pellingtonsalon' => '107parkavenue/salon',
    'pellingtonpremier' => '107parkavenue/premieretage',
    'pellingtonchambre' => '107parkavenue/chambre',
    'salledebain' => '107parkavenue/salledebain',
    'pellingtondeuxieme' => '107parkavenue/deuxiemeetage',
    'pellingtongrenier' => '107parkavenue/grenier',
    'pellingtoncave' => '107parkavenue/cave',
];
