<?php

return [
    'manoir/rdc' => 'rdc',
    'manoir/salon' => 'salon',
    'manoir/aile' => 'aile',
    'manoir/etage' => 'etage',
    'manoir/chambre' => 'chambre',
    'manoir/coffret' => 'coffret',
    'manoir/papier' => 'papier',
    'manoir/bureau' => 'bureau',
    'manoir/bureauprive' => 'bureauprive',
    'manoir/bureauprive2' => 'bureauprive2',
    'manoir/courtcircuit' => 'courtcircuit',
    'manoir/cuves' => 'cuves',
    'manoir/cavesecrete' => 'cavesecrete',
    'manoir/pensees' => 'pensees',
    'manoir/shoggoth' => 'shoggoth',
    'fin' => 'fin',
    'manoir/bibliotheque' => 'bibliotheque',
    'manoir/chambres' => 'chambres',
    'manoir/grenier' => 'grenier',
    'manoir/cave' => 'cave',
    'manoir/tableaubrule' => 'tableaubrule',
    'manoir/jardin' => 'jardin',
    'manoir/maisongaspard' => 'maisongaspard',
    'manoir/chenil' => 'chenil',
    'manoir/serre' => 'serre',
    'manoir/jour2' => 'jour2',
    'manoir/intrusion' => 'intrusion',
    'manoir/nuit' => 'nuit',
    'manoir/matin' => 'matin',
    'manoir/107parkavenue' => 'manoir107parkavenue',
    '107parkavenue/rdc' => 'pellingtonrdc',
    '107parkavenue/vestibule' => 'pellingtonvestibule',
    '107parkavenue/salon' => 'pellingtonsalon',
    '107parkavenue/premieretage' => 'pellingtonpremier',
    '107parkavenue/chambre' => 'pellingtonchambre',
    '107parkavenue/sdb' => 'salledebain',
    '107parkavenue/salledebain' => 'salledebain',
    '107parkavenue/deuxiemeetage' => 'pellingtondeuxieme',
    '107parkavenue/grenier' => 'pellingtongrenier',
    '107parkavenue/cave' => 'pellingtoncave',
];
