<?php

return [
    'index' => ['label' => 'Accueil'],
    'manuel' => ['label' => 'Manuel de pilote'],
    'andromede' => ['label' => 'Introduction'],
    'signal' => ['label' => 'Le signal'],
    'signalt' => ['label' => 'Traitement du signal'],
    'sas' => ['label' => 'Arrivée à GAEA-1'],
    'appontage' => ['label' => 'Appontage'],
    'hangar' => ['label' => 'Hangar'],
    'terminal' => ['label' => 'Terminal'],
    'hall' => ['label' => 'Hall principal'],
    'couloira' => ['label' => 'Couloir A'],
    'kurdiorb' => ['label' => 'Couloir B'],
    'kurdiorc' => ['label' => 'Couloir C'],
    'kurdiord' => ['label' => 'Couloir D'],
    'kurdiore' => ['label' => 'Couloir E'],
    'kurdiorf' => ['label' => 'Couloir F'],
    'kurdiorg' => ['label' => 'Couloir G'],
    'kurdiorh' => ['label' => 'Couloir H'],
    'drekrum' => ['label' => 'Bar'],
    'labratruma' => ['label' => 'Laboratoire A'],
    'labratrumb' => ['label' => 'Laboratoire B'],
    'spesrum' => ['label' => 'Mess'],
    'sovrum' => ['label' => 'Dortoir'],
    'raktrrum' => ['label' => 'Salle du Réacteur'],
    'sykkerum' => ['label' => 'Infirmerie'],
    'legerrum' => ['label' => 'Entrepôt'],
    'komunodek' => ['label' => 'Pont de Commandement'],
    'komuntrum' => ['label' => 'Cabine du Commandant'],
    'testfin' => ['label' => 'Fuir ou Mourir'],
    'plan' => ['label' => 'Plan de la station'],
];
