<?php

return [
    'index' => 'index',
    'manuel' => 'manuel',
    'andromede' => 'andromede',
    'signal' => 'signal',
    'signalt' => 'signalt',
    'sas' => 'sas',
    'appontage' => 'appontage',
    'hangar' => 'hangar',
    'terminal' => 'terminal',
    'hall' => 'hall',
    'couloira' => 'couloira',
    'kurdiorb' => 'kurdiorb',
    'kurdiorc' => 'kurdiorc',
    'kurdiord' => 'kurdiord',
    'kurdiore' => 'kurdiore',
    'kurdiorf' => 'kurdiorf',
    'kurdiorg' => 'kurdiorg',
    'kurdiorh' => 'kurdiorh',
    'drekrum' => 'drekrum',
    'labratruma' => 'labratruma',
    'labratrumb' => 'labratrumb',
    'spesrum' => 'spesrum',
    'sovrum' => 'sovrum',
    'raktrrum' => 'raktrrum',
    'sykkerum' => 'sykkerum',
    'legerrum' => 'legerrum',
    'komunodek' => 'komunodek',
    'komuntrum' => 'komuntrum',
    'testfin' => 'testfin',
    'plan' => 'plan',
];
