<?php

return [
    'q' => [
        'scene' => 'hangar',
        'label' => 'Hangar',
        'unknown_label' => 'Hangar',
        'visited_state' => 'hangar_visited',
        'neighbors' => ['r'],
        'enabled' => true,
    ],
    'r' => [
        'scene' => 'terminal',
        'label' => 'Terminal',
        'unknown_label' => 'Terminal',
        'visited_state' => 'terminal_visited',
        'neighbors' => ['q', 'l'],
        'enabled' => true,
    ],
    'l' => [
        'scene' => 'hall',
        'label' => 'Hall Principal',
        'unknown_label' => 'Hall Principal',
        'visited_state' => 'lvisited',
        'neighbors' => ['r', 'o', 'n', 'k', 'g', 'h', 's'],
        'enabled' => true,
    ],
    'o' => [
        'scene' => 'couloira',
        'label' => 'Couloir A',
        'unknown_label' => 'Couloir A',
        'visited_state' => 'ovisited',
        'event_state' => 'eventa',
        'neighbors' => ['l', 'r', 'h', 'n'],
        'enabled' => true,
    ],
    'n' => ['scene' => 'kurdiorb', 'label' => 'Couloir B', 'unknown_label' => 'Kurdior B', 'visited_state' => 'nvisited', 'tested_state' => 'ntested', 'neighbors' => ['l', 'o', 'j'], 'enabled' => true, 'blocked_without_power' => true],
    'k' => ['scene' => 'kurdiorc', 'label' => 'Couloir C', 'unknown_label' => 'Kurdior C', 'visited_state' => 'kvisited', 'tested_state' => 'ktested', 'neighbors' => ['l', 'f', 'j'], 'enabled' => true, 'oxygen_delta_on_first_visit' => -10],
    'f' => ['scene' => 'kurdiord', 'label' => 'Couloir D', 'unknown_label' => 'Kurdior D', 'visited_state' => 'fvisited', 'tested_state' => 'ftested', 'neighbors' => ['a', 'g', 'j', 'k'], 'enabled' => true, 'blocked_without_power' => true],
    'g' => ['scene' => 'kurdiore', 'label' => 'Couloir E', 'unknown_label' => 'Kurdior E', 'visited_state' => 'gvisited', 'tested_state' => 'gtested', 'neighbors' => ['l', 'b', 'c', 'f'], 'enabled' => true, 'blocked_without_power' => true],
    'h' => ['scene' => 'kurdiorf', 'label' => 'Couloir F', 'unknown_label' => 'Kurdior F', 'visited_state' => 'hvisited', 'tested_state' => 'htested', 'neighbors' => ['l', 'o', 'm', 'i'], 'enabled' => true, 'oxygen_delta_on_first_visit' => -10],
    's' => ['scene' => 'kurdiorg', 'label' => 'Couloir G', 'unknown_label' => 'Kurdior G', 'visited_state' => 'svisited', 'tested_state' => 'stested', 'neighbors' => ['l', 'p', 't'], 'enabled' => true, 'blocked_without_power' => true],
    'i' => ['scene' => 'kurdiorh', 'label' => 'Couloir H', 'unknown_label' => 'Kurdior H', 'visited_state' => 'ivisited', 'tested_state' => 'itested', 'neighbors' => ['h', 'm'], 'enabled' => true, 'blocked_without_power' => true],
    'b' => ['scene' => 'labratruma', 'label' => 'Laboratoire A', 'unknown_label' => 'Labratrum A', 'visited_state' => 'bvisited', 'tested_state' => 'btested', 'neighbors' => ['a', 'c', 'g'], 'enabled' => true],
    'a' => ['scene' => 'labratrumb', 'label' => 'Laboratoire B', 'unknown_label' => 'Labratrum B', 'visited_state' => 'avisited', 'tested_state' => 'atested', 'neighbors' => ['b', 'd', 'f'], 'enabled' => true],
    't' => ['scene' => 'spesrum', 'label' => 'Mess', 'unknown_label' => 'Spesrum', 'visited_state' => 'tvisited', 'tested_state' => 'ttested', 'neighbors' => ['p', 's'], 'enabled' => true],
    'm' => ['scene' => 'drekrum', 'label' => 'Bar', 'unknown_label' => 'Drekrum', 'visited_state' => 'mvisited', 'tested_state' => 'mtested', 'neighbors' => ['h', 'i', 'p'], 'enabled' => true, 'blocked_without_power' => true],
    'd' => ['scene' => 'sykkerum', 'label' => 'Infirmerie', 'unknown_label' => 'Sykkerum', 'visited_state' => 'dvisited', 'tested_state' => 'dtested', 'neighbors' => ['c', 'e', 'h'], 'enabled' => true, 'oxygen_delta_on_first_visit' => -10, 'event_state' => 'eventb', 'event_chance' => 10],
    'c' => ['scene' => 'sovrum', 'label' => 'Dortoir', 'unknown_label' => 'Sovrum', 'visited_state' => 'cvisited', 'tested_state' => 'ctested', 'neighbors' => ['b', 'd', 'g'], 'enabled' => true, 'blocked_without_power' => true],
    'p' => ['scene' => 'raktrrum', 'label' => 'Salle du Réacteur', 'unknown_label' => 'Raktrrum', 'visited_state' => 'pvisited', 'tested_state' => 'ptested', 'neighbors' => ['m', 's', 't'], 'enabled' => true],
    'j' => ['scene' => 'legerrum', 'label' => 'Entrepôt', 'unknown_label' => 'Legerrum', 'visited_state' => 'jvisited', 'tested_state' => 'jtested', 'neighbors' => ['f', 'k', 'n'], 'enabled' => true],
    'e' => ['scene' => 'komunodek', 'label' => 'Pont de Commandement', 'secondary_label' => 'Cabine du Commandant', 'unknown_label' => 'Komunodek', 'secondary_unknown_label' => 'Komuntrum', 'visited_state' => 'evisited', 'tested_state' => 'etested', 'neighbors' => ['d', 'i'], 'enabled' => true, 'mark_visited_on_entry' => false],
];
