<?php

return [
    'index' => ['label' => 'Introduction'],
    'sullivan_depart' => ['label' => 'Introduction - Sullivan'],
    'sullivan_tortuga' => ['label' => "L'Île de la Tortue"],
    'sullivan_marche' => ['label' => 'Le Marché'],
    'sullivan_bordel' => ['label' => 'Le Bordel'],
    'sullivan_taverne' => ['label' => 'La Taverne'],
    'sullivan_docks' => ['label' => 'Les Docks'],
    'sullivan_bibliotheque' => ['label' => 'La Bibliothèque'],
    'sullivan_embrouilles' => ['label' => 'Embrouilles'],
    'sullivan_embarquement' => ['label' => 'Embarquement'],
    'sullivan_flots' => ['label' => 'Sur les Flots'],
    'sullivan_pontprincipal' => ['label' => 'Pont principal'],
    'sullivan_dunette' => ['label' => 'Dunette'],
    'sullivan_pontinferieur' => ['label' => 'Pont inférieur'],
    'sullivan_mess' => ['label' => 'Mess'],
    'sullivan_quartierdesequipages' => ['label' => 'Quartier des équipages'],
    'sullivan_cale' => ['label' => 'Cale'],
    'sullivan_cabine' => ['label' => 'Cabine du capitaine'],
    'sullivan_tempete' => ['label' => 'Tempête'],
    'sullivan_plage' => ['label' => 'Plage'],
    'sullivan_grottestorchesallumees' => ['label' => 'Grottes'],
    'sullivan_grottestorcheseteintes' => ['label' => 'Grottes'],
    'sullivan_portescite' => ['label' => 'Portes de la Cité'],
    'logan_depart' => ['label' => 'Introduction - Logan'],
    'logan_bibliotheque' => ['label' => 'La Bibliothèque'],
    'logan_fuite' => ['label' => 'Fuite'],
    'logan_taverne' => ['label' => 'La Taverne'],
    'logan_embrouilles' => ['label' => 'Embrouilles'],
    'logan_embarquement' => ['label' => 'Embarquement'],
    'logan_flots' => ['label' => 'Sur les Flots'],
    'logan_pontprincipal' => ['label' => 'Pont principal'],
    'logan_dunette' => ['label' => 'Dunette'],
    'logan_pontinferieur' => ['label' => 'Pont inférieur'],
    'logan_mess' => ['label' => 'Mess'],
    'logan_quartierdesequipages' => ['label' => 'Quartier des équipages'],
    'logan_cale' => ['label' => 'Cale'],
    'logan_cabine' => ['label' => 'Cabine du capitaine'],
    'logan_tempete' => ['label' => 'Tempête'],
    'logan_plage' => ['label' => 'Plage'],
    'logan_grottestorchesallumees' => ['label' => 'Grottes'],
    'logan_grottestorcheseteintes' => ['label' => 'Grottes'],
    'logan_portescite' => ['label' => 'Portes de la Cité'],
    'logan_cite' => ['label' => 'Cité'],
    'logan_gardien' => ['label' => 'Le Gardien'],
    'logan_pyramide' => ['label' => 'Pyramide'],
    'logan_mutinerie' => ['label' => 'Mutinerie'],
    'logan_fin' => ['label' => 'Fin'],
];
