<?php
	$loggedin = $_SESSION['loggedin'] ?? null;
	$idcompte = $_SESSION['idcompte'] ?? null;
	session_unset();
	session_destroy();
	session_start();
	if ($loggedin !== null) { $_SESSION['loggedin'] = $loggedin; }
	if ($idcompte !== null) { $_SESSION['idcompte'] = $idcompte; }
	
	$_SESSION['jour'] = false;
	$_SESSION['visitepellington'] = false; // Le joueur n'est pas encore allé chez Pellington
	$_SESSION['sdi'] = false;
	$_SESSION['sad'] = false;
	$_SESSION['sev'] = false;
	$_SESSION['spo'] = false;
	$_SESSION['sse'] = false;
	$_SESSION['coffret'] = false; // Le coffret n'a pas été récupéré dans l'inventaire ou l'énigme est terminée
	$_SESSION['papier'] = false; // Le papier n'a pas été récupéré dans le coffret ou l'énigme est terminée
	$_SESSION['journal1'] = false;
	$_SESSION['journal2'] = false;
	$_SESSION['journal3'] = false;
	$_SESSION['journal4'] = false;
	$_SESSION['journal5'] = false;
	$_SESSION['journal6'] = false;
	$_SESSION['journal7'] = false;
	$_SESSION['journal8'] = false;
	$_SESSION['journal9'] = false;
	$_SESSION['fouillevestibule'] = false; // Le joueur n'a pas encore tout trouvé dans le vestibule de Pellington
	$_SESSION['flacon'] = false; // Le flacon de barbiturique n'a pas été trouvé dans la veste de Pellington qui peut encore être fouillée
	$_SESSION['recette'] = false; // La recette n'a pas été trouvée, le laboratoire de Pellington peut encore être fouillé
	$_SESSION['antidote'] = false; // L'antidote n'a pas été fabriqué, l'énigme de la salle de bain est accessible
	$_SESSION['armoireopened'] = false; // Le joueur n'a pas trouvé l'armoire à pharmacie
	$_SESSION['chiensmalades'] = false;
	$_SESSION['chiensemp'] = false; // Le fait que les chiens ont été empoisonnés n'a pas été découvert
	$_SESSION['chienssauves'] = false; // Les chiens n'ont pas encore été guéris
	$_SESSION['chienssauvesfin'] = false; // Les chiens sont guéris mais les joueurs ne sont pas encore allé voir Gaspard pour obtenir leur récompense. La fin alternative n'est pas débloquée.
	$_SESSION['intrusion'] = false; // L'intrusion n'a pas encore eu lieu et les chiens ne sont pas encore empoisonnés
	$_SESSION['scof'] = false; // Le coffre-fort n'a pas été découvert
	$_SESSION['tab'] = false; // Le joueur n'a pas cherché le tableau dans le salon
	$_SESSION['aveux'] = false; // Le joueur n'a pas encore récupéré les aveux de Pellington
	$_SESSION['magna'] = false; // Le Magna Mater n'a pas encore été trouvé
	$_SESSION['restab'] = false; // Le joueur n'a pas encore trouvé les restes du tableau dans la cave
	$_SESSION['coffrenigme'] = false; // Le joueur n'a pas trouvé toutes les pièces ou ne les a pas encore utilisées
	$_SESSION['oldcle'] = false; // Le joueur n'a pas encore ouvert le coffre-fort et récupéré la clé qui est dedans pour la trappe
	$_SESSION['petitecle'] = false; // Le joueur n'a pas encore récupéré la clé dans le coffret pour le tiroir du bureau
	$_SESSION['bureauprive'] = false; // Le joueur n'a pas encore réussi à entrer dans le bureau privé
	$_SESSION['tiroiropened'] = false; // Le joueur n'a pas encore trouvé le journal dans le tiroir du bureau
	$_SESSION['trappe'] = false; // Le joueur n'a pas encore trouvé la trappe dans le bureau privé
	$_SESSION['trappeopen'] = false; // Le joueur n'a pas encore ouvert la trappe
	$_SESSION['cuves'] = false; // Le joueur n'a pas essayé d'activer les cuves
	$_SESSION['refus'] = false; // Le joueur n'a pas refusé d'activer les cuves
	$_SESSION['verite'] = false; // Le joueur n'a pas encore découvert l'horrible vérité sur les événements
	$_SESSION['restab'] = false; // Le joueur n'a pas encore récupéré les morceaux de tableau brûlé
	$_SESSION['templar'] = false; // Le joueur n'a pas encore trouvé le code des templiers
	$_SESSION['shortcut'] = false; // Le joueur n'a pas encore accédé à l'énigme du court-circuit
	$_SESSION['masseactive'] = false; // Le joueur n'a pas joué avec l'électricité pour attiser le shoggoth
	$_SESSION['grenierpiano'] = false; // Le joueur n'a pas encore ouvert le piano
	$_SESSION['chiensmal'] = false; // Les chiens sont malades mais le joueur n'a pas averti Gaspard
	$_SESSION['pnakotiques'] = false; // Le joueur n'a pas trouvé la formule de rituel
	$_SESSION['pnakotiquesnotes'] = false; // Le joueur n'a pas trouvé la formule de rituel
	$_SESSION['rituelg'] = false; // Le rituel n'est pas en cours pour obtenir la bonne fin
	$_SESSION['rituelnb'] = false; // Le rituel n'est pas en cours pour la fin neutralbad
	$_SESSION['end'] = false; // Le joueur n'est pas au dernier chapitre du jeu
	$_SESSION['talisman'] = false;
	$_SESSION['telephone'] = false;
	$_SESSION['coffreindice1'] = false;
	$_SESSION['coffreindice2'] = false;
	$_SESSION['coffreindice3'] = false;
	$_SESSION['coffrereponse'] = false;
	$_SESSION['coffrefortouvert'] = false; // Le joueur n'a pas encore ouvert le coffre-fort
	$_SESSION['mdp1'] = false;
	$_SESSION['mdp2'] = false;
	$_SESSION['mdp3'] = false;
	$_SESSION['mdp4'] = false;
	$_SESSION['mdp5'] = false;
	$_SESSION['mdp6'] = false;
	$_SESSION['mdp7'] = false;
	$_SESSION['mdp8'] = false;
	$_SESSION['mdp9'] = false;
	$_SESSION['mdp10'] = false;
	$_SESSION['mdp11'] = false;
	$_SESSION['mdp12'] = false;
	$_SESSION['mdp13'] = false;
	$_SESSION['mdp14'] = false;
	$_SESSION['mdp15'] = false;
	$_SESSION['mdp16'] = false;
	$_SESSION['mdp17'] = false;
	$_SESSION['mdp18'] = false;
	$_SESSION['mdp19'] = false;
	$_SESSION['mdp20'] = false;
	$_SESSION['mdp21'] = false;
	$_SESSION['mdp22'] = false;
	$_SESSION['mdp23'] = false;
	$_SESSION['mdp24'] = false;
	$_SESSION['mdp25'] = false;
	$_SESSION['mdp26'] = false;
	$_SESSION['mdp27'] = false;
	$_SESSION['mdp28'] = false;
	$_SESSION['mdp29'] = false;
	$_SESSION['mdp30'] = false;
	$_SESSION['mdp31'] = false;
	$_SESSION['mdp32'] = false;
	$_SESSION['mdp33'] = false;
	$_SESSION['fin'] = false;
?>
