<?php

use App\Services\Adventures\Scenarios\SecretsFamiliaux\SecretsFamiliauxAdventureFlow;

return [
    'slug' => 'secretsfamiliaux',
    'title' => 'Secrets Familiaux',
    'layout' => 'adventure',
    'flow' => SecretsFamiliauxAdventureFlow::class,
    'content_path' => 'Adventures/SecretsFamiliaux',
    'styles' => [
        'assets/styles/aventures/secrets_familiaux/style.css',
        'assets/styles/aventures/secrets_familiaux/armoire_pharmacie.css',
        'assets/styles/aventures/secrets_familiaux/bureau.css',
        'assets/styles/aventures/secrets_familiaux/cercle_rituel.css',
        'assets/styles/aventures/secrets_familiaux/chambre.css',
        'assets/styles/aventures/secrets_familiaux/drag_drop_coffret.css',
        'assets/styles/aventures/secrets_familiaux/drag_drop_electricite.css',
        'assets/styles/aventures/secrets_familiaux/trousseau_cles.css',
    ],
    'sidebar_view' => 'adventures/secretsfamiliaux/sidebar',
    'footer_view' => 'adventures/secretsfamiliaux/footer',
    'entry_scene' => 'index',
    'scene_aliases' => [
        'manoir/rdc' => 'rdc',
        'manoir/salon' => 'salon',
        'manoir/aile' => 'aile',
        'manoir/etage' => 'etage',
        'manoir/chambre' => 'chambre',
        'manoir/coffret' => 'coffret',
        'manoir/papier' => 'papier',
        'manoir/bureau' => 'bureau',
        'manoir/bureauprive' => 'bureauprive',
        'manoir/bureauprive2' => 'bureauprive2',
        'manoir/courtcircuit' => 'courtcircuit',
        'manoir/cuves' => 'cuves',
        'manoir/cavesecrete' => 'cavesecrete',
        'manoir/pensees' => 'pensees',
        'manoir/shoggoth' => 'shoggoth',
        'manoir/bibliotheque' => 'bibliotheque',
        'manoir/chambres' => 'chambres',
        'manoir/grenier' => 'grenier',
        'manoir/cave' => 'cave',
        'manoir/jardin' => 'jardin',
        'manoir/maisongaspard' => 'maisongaspard',
        'manoir/chenil' => 'chenil',
        'manoir/serre' => 'serre',
        'manoir/jour2' => 'jour2',
        'manoir/intrusion' => 'intrusion',
        'manoir/nuit' => 'nuit',
        'manoir/matin' => 'matin',
        'manoir/107parkavenue' => 'manoir107parkavenue',
        '107parkavenue/rdc' => 'pellingtonrdc',
        '107parkavenue/vestibule' => 'pellingtonvestibule',
        '107parkavenue/salon' => 'pellingtonsalon',
        '107parkavenue/premieretage' => 'pellingtonpremier',
        '107parkavenue/chambre' => 'pellingtonchambre',
        '107parkavenue/sdb' => 'salledebain',
        '107parkavenue/salledebain' => 'salledebain',
        '107parkavenue/deuxiemeetage' => 'pellingtondeuxieme',
        '107parkavenue/grenier' => 'pellingtongrenier',
        '107parkavenue/cave' => 'pellingtoncave',
    ],
    'scene_urls' => [
        'rdc' => 'manoir/rdc',
        'salon' => 'manoir/salon',
        'aile' => 'manoir/aile',
        'etage' => 'manoir/etage',
        'chambre' => 'manoir/chambre',
        'coffret' => 'manoir/coffret',
        'papier' => 'manoir/papier',
        'bureau' => 'manoir/bureau',
        'bureauprive' => 'manoir/bureauprive',
        'bureauprive2' => 'manoir/bureauprive2',
        'courtcircuit' => 'manoir/courtcircuit',
        'cuves' => 'manoir/cuves',
        'cavesecrete' => 'manoir/cavesecrete',
        'pensees' => 'manoir/pensees',
        'shoggoth' => 'manoir/shoggoth',
        'bibliotheque' => 'manoir/bibliotheque',
        'chambres' => 'manoir/chambres',
        'grenier' => 'manoir/grenier',
        'cave' => 'manoir/cave',
        'jardin' => 'manoir/jardin',
        'maisongaspard' => 'manoir/maisongaspard',
        'chenil' => 'manoir/chenil',
        'serre' => 'manoir/serre',
        'jour2' => 'manoir/jour2',
        'intrusion' => 'manoir/intrusion',
        'nuit' => 'manoir/nuit',
        'matin' => 'manoir/matin',
        'manoir107parkavenue' => 'manoir/107parkavenue',
        'pellingtonrdc' => '107parkavenue/rdc',
        'pellingtonvestibule' => '107parkavenue/vestibule',
        'pellingtonsalon' => '107parkavenue/salon',
        'pellingtonpremier' => '107parkavenue/premieretage',
        'pellingtonchambre' => '107parkavenue/chambre',
        'salledebain' => '107parkavenue/salledebain',
        'pellingtondeuxieme' => '107parkavenue/deuxiemeetage',
        'pellingtongrenier' => '107parkavenue/grenier',
        'pellingtoncave' => '107parkavenue/cave',
    ],
    'content_files' => [
        'rdc' => 'manoir/rdc',
        'salon' => 'manoir/salon',
        'aile' => 'manoir/aile',
        'etage' => 'manoir/etage',
        'chambre' => 'manoir/chambre',
        'coffret' => 'manoir/coffret',
        'papier' => 'manoir/papier',
        'bureau' => 'manoir/bureau',
        'bureauprive' => 'manoir/bureauprive',
        'bureauprive2' => 'manoir/bureauprive2',
        'courtcircuit' => 'manoir/courtcircuit',
        'cuves' => 'manoir/cuves',
        'cavesecrete' => 'manoir/cavesecrete',
        'pensees' => 'manoir/pensees',
        'shoggoth' => 'manoir/shoggoth',
        'bibliotheque' => 'manoir/bibliotheque',
        'chambres' => 'manoir/chambres',
        'grenier' => 'manoir/grenier',
        'cave' => 'manoir/cave',
        'jardin' => 'manoir/jardin',
        'maisongaspard' => 'manoir/maisongaspard',
        'chenil' => 'manoir/chenil',
        'serre' => 'manoir/serre',
        'jour2' => 'manoir/jour2',
        'intrusion' => 'manoir/intrusion',
        'nuit' => 'manoir/nuit',
        'matin' => 'manoir/matin',
        'manoir107parkavenue' => 'manoir/107parkavenue',
        'pellingtonrdc' => '107parkavenue/rdc',
        'pellingtonvestibule' => '107parkavenue/vestibule',
        'pellingtonsalon' => '107parkavenue/salon',
        'pellingtonpremier' => '107parkavenue/premieretage',
        'pellingtonchambre' => '107parkavenue/chambre',
        'salledebain' => '107parkavenue/salledebain',
        'pellingtondeuxieme' => '107parkavenue/deuxiemeetage',
        'pellingtongrenier' => '107parkavenue/grenier',
        'pellingtoncave' => '107parkavenue/cave',
    ],
    'scenes' => [
        'index' => 'Introduction',
        'cimetiere' => 'Cimetière',
        '15hamiltonstreet' => 'Manoir',
        'manor' => 'Manoir',
        'manoirint' => 'Manoir',
        'rdc' => 'Rez-de-chaussée',
        'salon' => 'Salon',
        'aile' => 'Aile des domestiques',
        'etage' => 'Étage',
        'chambre' => 'Chambre de William',
        'coffret' => 'Coffret',
        'papier' => 'Papier',
        'bureau' => 'Bureau',
        'bureauprive' => 'Bureau privé',
        'bureauprive2' => 'Laboratoire privé',
        'courtcircuit' => 'Système électrique',
        'cuves' => 'Cuves',
        'cavesecrete' => 'Cave secrète',
        'pensees' => 'Pensées',
        'shoggoth' => 'Retour au manoir',
        'bibliotheque' => 'Bibliothèque',
        'chambres' => 'Chambres',
        'grenier' => 'Grenier',
        'cave' => 'Cave',
        'jardin' => 'Jardin',
        'maisongaspard' => 'Maison de Gaspard',
        'chenil' => 'Chenil',
        'serre' => 'Serre',
        'jour2' => 'Jour 2',
        'intrusion' => 'Intrusion',
        'nuit' => 'Pendant la nuit',
        'matin' => 'Matin',
        'manoir107parkavenue' => 'Chez Pellington',
        '107parkavenue' => 'Chez Pellington',
        'pellingtonrdc' => 'Chez Pellington',
        'pellingtonvestibule' => 'Vestibule',
        'pellingtonsalon' => 'Salon',
        'pellingtonpremier' => 'Premier étage',
        'pellingtonchambre' => 'Chambre du docteur',
        'salledebain' => 'Salle de bain',
        'pellingtondeuxieme' => 'Deuxième étage',
        'pellingtongrenier' => 'Grenier',
        'pellingtoncave' => 'Cave',
    ],
    'state' => [
        'defaults' => [
            '_scene' => 'index',
            'started' => false,
            'index_step' => 0,
            'cimetiere_step' => 0,
            'cimetiere_truth_step' => 0,
            'manoir_step' => 0,
            'manoir_keys' => false,
            'manoirint_step' => 0,
            'salon_step' => 0,
            'salon_tableau_found' => false,
            'aile_response' => null,
            'chambre_step' => 0,
            'chambre_coffre_seen' => false,
            'chambre_safe_step' => 0,
            'chambre_safe_combination' => '',
            'chambre_safe_opened' => false,
            'chambre_coffret_taken' => false,
            'coffret_step' => 0,
            'coffret_opened' => false,
            'papier_step' => 0,
            'bureau_step' => 0,
            'bureau_private_unlocked' => false,
            'bureauprive_step' => 0,
            'bureauprive_tiroir_opened' => false,
            'bureauprive_pnakotiques_found' => false,
            'bureauprive2_step' => 0,
            'bureauprive2_trappe_found' => false,
            'bureauprive2_trappe_opened' => false,
            'bureauprive2_refus' => false,
            'cavesecrete_visited' => false,
            'courtcircuit_step' => 0,
            'electricity_restored' => false,
            'cuves_step' => 0,
            'cuves_seen' => false,
            'masse_active' => false,
            'cavesecrete_step' => 0,
            'cavesecrete_response' => null,
            'pensees_step' => 0,
            'pensees_response' => null,
            'truth_discovered' => false,
            'shoggoth_step' => 0,
            'shoggoth_ending' => null,
            'bibliotheque_response' => null,
            'bibliotheque_magna' => false,
            'bibliotheque_templar' => false,
            'grenier_step' => 0,
            'grenier_piano_open' => false,
            'cave_response' => null,
            'cave_tableau_found' => false,
            'gaspard_response' => null,
            'jour2_step' => 0,
            'manor_day' => false,
            'intrusion_step' => 0,
            'intrusion_done' => false,
            'chiens_malades' => false,
            'chiens_empoisonnes' => false,
            'chiens_poisoning_discovered' => false,
            'chiens_sauves' => false,
            'chiens_sauves_fin' => false,
            'nuit_step' => 0,
            'matin_step' => 0,
            'manoir107parkavenue_step' => 0,
            'police_authenticated' => false,
            'pellington_step' => 0,
            'pellingtonrdc_step' => 0,
            'pellington_vestibule_step' => 0,
            'pellington_veste_searched' => false,
            'pellington_vestibule_done' => false,
            'pellington_salon_step' => 0,
            'pellington_premier_step' => 0,
            'pellington_chambre_step' => 0,
            'pellington_salledebain_step' => 0,
            'pellington_armoire_opened' => false,
            'pellington_deuxieme_step' => 0,
            'pellington_recette_found' => false,
            'pellington_grenier_step' => 0,
            'pellington_cave_step' => 0,
            'pellington_visit' => false,
            'hints' => [],
            'inventory' => [],
            'notes' => [],
        ],
    ],
    'assets' => [
        'banner' => 'assets/img/secrets/secretsfamiliauxmini.png',
    ],
    'inventory_items' => [
        'piecepo' => [
            'image' => 'assets/img/secrets/po.png',
            'alt' => 'Une pièce avec une pomme.',
        ],
        'piecead' => [
            'image' => 'assets/img/secrets/ad.png',
            'alt' => "Une pièce avec une tête d'homme.",
        ],
        'pieceev' => [
            'image' => 'assets/img/secrets/ev.png',
            'alt' => 'Une pièce avec une tête de femme.',
        ],
        'magnamater' => [
            'image' => 'assets/img/secrets/magnamater.png',
            'alt' => 'Le Magna Mater.',
        ],
        'templar' => [
            'image' => 'assets/img/secrets/templar.png',
            'alt' => "Un papier avec l'explication d'un code.",
        ],
        'tableaubrule' => [
            'image' => 'assets/img/secrets/tableaubrule.png',
            'alt' => "Les morceaux d'un tableau brûlé.",
        ],
        'analeptique' => [
            'image' => 'assets/img/secrets/analeptique.png',
            'alt' => 'Un analeptique pour guérir les chiens empoisonnés.',
        ],
        'flacon' => [
            'image' => 'assets/img/secrets/flacon.png',
            'alt' => 'Un flacon de barbiturique vide.',
        ],
        'recette' => [
            'image' => 'assets/img/secrets/recette.png',
            'alt' => 'Une recette indiquant comment fabriquer un médicament.',
        ],
        'aveux' => [
            'image' => 'assets/img/secrets/aveux.png',
            'alt' => 'Les aveux du docteur Pellington.',
        ],
        'piecese' => [
            'image' => 'assets/img/secrets/se.png',
            'alt' => 'Une pièce avec un serpent.',
        ],
        'piecedi' => [
            'image' => 'assets/img/secrets/di.png',
            'alt' => 'Une pièce représentant un vieil homme.',
        ],
        'oldcle' => [
            'image' => 'assets/img/secrets/oldcle.png',
            'alt' => 'Une vieille clé rouillée.',
        ],
        'coffret' => [
            'image' => 'assets/img/secrets/coffret.png',
            'alt' => 'Un petit coffret ouvragé.',
        ],
        'papier' => [
            'image' => 'assets/img/secrets/papier.png',
            'alt' => 'Un morceau de papier avec une inscription étrange.',
        ],
        'petitecle' => [
            'image' => 'assets/img/secrets/petitecle.png',
            'alt' => 'Une petite clé.',
        ],
        'talisman' => [
            'image' => 'assets/img/secrets/talisman.png',
            'alt' => 'Un étrange talisman confié par Gaspard.',
        ],
        'journal1' => [
            'image' => 'assets/img/secrets/journal1.png',
            'alt' => "La première page du journal de l'oncle William.",
        ],
        'journal2' => [
            'image' => 'assets/img/secrets/journal2.png',
            'alt' => "La deuxième page du journal de l'oncle William.",
        ],
        'journal3' => [
            'image' => 'assets/img/secrets/journal3.png',
            'alt' => "La troisième page du journal de l'oncle William.",
        ],
        'journal4' => [
            'image' => 'assets/img/secrets/journal4.png',
            'alt' => "La quatrième page du journal de l'oncle William.",
        ],
        'journal5' => [
            'image' => 'assets/img/secrets/journal5.png',
            'alt' => "La cinquième page du journal de l'oncle William.",
        ],
        'journal6' => [
            'image' => 'assets/img/secrets/journal6.png',
            'alt' => "La sixième page du journal de l'oncle William.",
        ],
        'journal7' => [
            'image' => 'assets/img/secrets/journal7.png',
            'alt' => "La septième page du journal de l'oncle William.",
        ],
        'journal8' => [
            'image' => 'assets/img/secrets/journal8.png',
            'alt' => "La huitième page du journal de l'oncle William.",
        ],
        'journal9' => [
            'image' => 'assets/img/secrets/journal9.png',
            'alt' => "La neuvième page du journal de l'oncle William.",
        ],
        'pnakotiques' => [
            'image' => 'assets/img/secrets/pnakotiques.png',
            'alt' => 'Une page des Manuscrits Pnakotiques.',
        ],
        'pnakotiquesnotes' => [
            'image' => 'assets/img/secrets/pnakotiquesnotes.png',
            'alt' => 'Une page de notes sur les Manuscrits Pnakotiques.',
        ],
    ],
];
